### ISSUE TITLE
raspbian stretch support?

### ISSUE THREAD

**Issue by tonyzzz321** [patrikolausson/dispmanx_vnc#13]
The new debian release stretch has changed some of the library files that dispmanx_vnc uses, namely libGLESv2.so and libEGL.so. This causes dispmanx_vnc to failed to build because of the missing libraries. after installing libgles2-mesa and libsdl2-dev with "apt-get install libgles2-mesa libsdl2-dev", the missing library error is gone but there is new undefined reference error. The following is the output of "make":

g++ -Wall -std=c++11 -O3 -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -o dispmanx_vncserver main.o UFile.o DMXResource.o DMXDisplay.o DMXKeyboard.o DMXMouse.o DMXVNCServer.o -L/opt/vc/lib/ -lGLESv2 -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lvncserver -lconfig++
main.o: In function `ReadConfigFile(char const*, std::string const&, ConfigData&)':
main.cpp:(.text+0x6dc): undefined reference to `libconfig::Config::lookupValue(char const*, std::string&) const'
main.cpp:(.text+0x71c): undefined reference to `libconfig::Config::lookupValue(char const*, std::string&) const'
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'dispmanx_vncserver' failed
make: *** [dispmanx_vncserver] Error 1

I think maybe the new library installed is not exactly the same as the old library used to be on debian jessie, so not compatible?
Is there any plan on supporting debian stretch?

**Comment by rccavalcanti** [comment]
I could compile on Stretch after installing libgles2-mesa-dev.

**Comment by matthew-brett** [comment]
Only to ask - do we expect worse performance, if we are using software GL via mesa, rather than the GL libraries?  I mean, is there a reason to prefer the library renames here:

 https://raspberrypi.stackexchange.com/questions/77619/where-is-legl-lglesv2

to installing and linking against `libgles2-mesa-dev`?

If so then, it would be good to pick up the correct library names without patching the Makefile (that's what I did).  Otherwise, it would be good to mention the need for `libgles2-mesa-dev` on Stretch.
